### ISSUE TITLE
How to access to current controller

### ISSUE THREAD

**Issue by AliAmini** [chaclee/ci-blade#1]
Hi
I noticed that we can not access to the current controller via `$this`; How to access to controller?
Thanks a lot

**Comment by rainwsy** [comment]
Can you explain it in more detail?

**Comment by chaclee** [comment]
@AliAmini Can you explain it in more detail? or a demo?

**Comment by AliAmini** [comment]
I want to access to the instance of $CI (CodeIgniter) object in view, but I didn't find any way for it!
an example: 
```
// views/email.blade.php
@extends('layouts.default')

@section('content')
	<h3>Send Mail</h3>
	{!!var_dump($this)!!}
	{{$this->session->userdata('email_sent')}}
	{{-- Some Codes --}}
@stop
```
and the result:
![git1](https://cloud.githubusercontent.com/assets/7336518/22512024/dd3aa6e6-e8ac-11e6-8888-e4736280cdd4.PNG)

and `cache/views/16cdd2977637cdabec98a343ee41a0da`:
```
<?php $__env->startSection('content'); ?>
	<h3>Send Mail</h3>
	<?php echo var_dump($this); ?>

	<?php echo e($this->session->userdata('email_sent')); ?>

	<?php echo form_open('/email/sendMail'); ?>
    <?php 
    /** 
     * some codes here
   **/
    ?>
```

I'm looking for instance of `$CI` object but that's not exist. You can add a copy of `$CI` object to `Xiaoler\Blade\Engines\CompilerEngine`.

Thanks a lot

**Comment by chaclee** [comment]
@AliAmini 

if you want to use  `$this` in view,you should
```
$vars = ['this'=>$this];
$this->blade->view('welcome_message', $vars);
```

But I don't recommend doing this.

**Comment by AliAmini** [comment]
Thanks
I did this:
```
$vars = ['CI'=>$this];
$this->blade->view('welcome_message', $vars);
```
